version: 0.0
os: linux

files:
  - source: otopuraapp/build/          # 同期元
    destination: /usr/share/nginx/html # 同期先
  - source: otopuraapp/media/          # 同期元
    destination: /usr/share/nginx/html/media # 同期先
permissions:
  - object: /usr/share/nginx/html
    owner: ec2-user
    group: root
    mode: 755
    type:
      - directory
  - object: /usr/share/nginx/html
    owner: ec2-user
    group: root
    mode: 644
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: root

