# Generated by Django 3.2.6 on 2021-11-21 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otopuraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dm', models.TextField(blank=True, max_length=1000, null=True, verbose_name='')),
                ('dm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_user_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
