# Generated by Django 3.2.6 on 2022-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otopuraapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='cm_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
