# Generated by Django 3.2.6 on 2022-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otopuraapp', '0003_remove_commentmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandmodel',
            old_name='part',
            new_name='part_1',
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='part_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='part_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='part_4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='part_5',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
