# Generated by Django 3.2.6 on 2022-04-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otopuraapp', '0004_auto_20220426_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmodel',
            name='part_1',
        ),
        migrations.RemoveField(
            model_name='bandmodel',
            name='part_2',
        ),
        migrations.RemoveField(
            model_name='bandmodel',
            name='part_3',
        ),
        migrations.RemoveField(
            model_name='bandmodel',
            name='part_4',
        ),
        migrations.RemoveField(
            model_name='bandmodel',
            name='part_5',
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='base',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='drum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='guitar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='keyboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bandmodel',
            name='vocal',
            field=models.BooleanField(default=False),
        ),
    ]
