# Generated by Django 3.2.6 on 2022-05-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otopuraapp', '0006_auto_20220505_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='cm_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cm_band', to='otopuraapp.bandmodel'),
        ),
        migrations.AlterField(
            model_name='goodmodel',
            name='good_band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_band', to='otopuraapp.bandmodel'),
        ),
    ]
